# -*- coding: utf-8 -*-
"""NLP_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gREi_RZprvOh3MZWP3wjol29au2Vl-8R
"""



import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle

app = Flask(__name__)
@app.route('/')
def home():
    return render_template('index.html')

'''
@app.route('/')
def home():
    return render_template('index.html',template_folder='/GD/My Drive/templates')

@app.route('/predict',methods=['POST'])
def predict():
    if request.form['action'] == 'getinputfields':
        
        inputted_string=request.form["question"]
        output=getPrediction([inputted_string,'','',''])[0]
  
    return render_template('index.html', prediction_text=output)
'''


if __name__ == "__main__":
    app.run(debug=True)

